/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG__cl_py_WRAP_H_
#define SWIG__cl_py_WRAP_H_


class SwigDirector_HitCollector : public lucene::search::HitCollector, public Swig::Director {

public:
    SwigDirector_HitCollector(PyObject* self, bool disown = false);
    virtual void collect(int const doc, float const score);
};


class SwigDirector_Filter : public lucene::search::Filter, public Swig::Director {

public:
    SwigDirector_Filter(PyObject* self, bool disown = false);
    virtual lucene::util::BitSet *bits(lucene::index::IndexReader &reader) const;
};


class SwigDirector_Analyzer : public lucene::analysis::Analyzer, public Swig::Director {

public:
    SwigDirector_Analyzer(PyObject* self, bool disown = false);
    virtual lucene::analysis::TokenStream &tokenStream(char const *fieldName, lucene::util::Reader *reader);
};


#endif
